### PR TITLE
Add description for seq-tools checks

### PR DESCRIPTION
**Pull request by edsu7**
English is hard. Give the document a read through and check whether it makes sense.

### CODE REVIEW

**Comment by lindaxiang** [comment]
> English is hard. Give the document a read through and check whether it makes sense.

💯

**Comment by lindaxiang** [comment]
> > English is hard. Give the document a read through and check whether it makes sense.
> 
> 💯

Hi @edsu7 @hknahal  , I reorganize part of the content in README.md into the wiki pages, so that the validation checks are more visible  to the users. Can you take a look and add the validation rules for each check?
https://github.com/icgc-argo/seq-tools/wiki

**Comment by lindaxiang** [comment]
The details of seq-tools checks have been moved to Wiki: https://github.com/icgc-argo/seq-tools/wiki
However we will add a brief text in Readme to direct user to wiki.

**Comment by edsu7** [comment]
Added [README.md](https://github.com/icgc-argo/seq-tools/blob/main/seq_tools/validation/README.md)

**Comment by edsu7** [comment]
Information was populated into wiki instead. No longer needed.

**Pull request closed without merging**
